Output assets/demo.gif

Require culprit
Require bat

Set Shell "bash"
Set FontSize 32
Set Width 1400
Set Height 600
Set PlaybackSpeed 0.5

Type "culprit clean -o cleanup.sh" Sleep 500ms Enter
Wait+Screen /created/
Sleep 200ms

Type "bat cleanup.sh" Sleep 500ms Enter

Sleep 1s

Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms
Down
Sleep 100ms

Sleep 500ms
